### PR TITLE
merge from master; update gfx test reference images

### PR DESCRIPTION
**Pull request by mykmelez**
This branch currently contains two changes:

1. merge from master;
2. set the background color of some gfx test reference images to white.

With that second change, all tests now pass on the branch.

Regarding that second change, it isn't entirely clear, but it looks like Chameleon sets the background color of a *Canvas* to `black`, while the non-Chameleon impl sets it to `white`. I didn't actually find the specific code that does it, but I did see a ton of code in Chameleon to set the background color of various displayables, and basically no code at all to do that in the non-Chameleon impl, which presumably just delegates it to the native impl.

Regardless, it doesn't seem to make a difference for midlets I've tested, like Asteroids.  So this change updates the gfx reference images to have white backgrounds (for the images whose backgrounds are visible).

Note that some gfx tests now pass on my Mac with fewer different pixels than the max allowed (mostly because I created the new reference images on that machine):

* AlertTest PASS - 0 <= 3111
* CanvasTest PASS - 0 <= 271
* ImageRenderingTest PASS - 0 <= 266
* DrawAndFillRoundRectTest PASS - 0 <= 2000
* DrawAndFillArcTest PASS - 0 <= 2000
* ImageProcessingTest PASS - 0 <= 6184
* DrawLineOffscreenCanvasTest PASS - 1376 <= 1500

We should audit their behavior on Travis and update their *maxDifferent* values accordingly.

### CODE REVIEW

**Comment by mykmelez** [comment]
Oh, and I made the gfx tests a bit more verbose, so they output both the number of different pixels and the maximum number allowed.

**Comment by mykmelez** [comment]
Finally, ef6b1bd prevents the indeterminate progress meter (throbber) from triggering a scrollbar in the alert dialog when its height changes as a result of the CSS "rotate" animation.

**Comment by marco-c** [comment]
The Chameleon implementation draws a black background on the canvas before calling the Canvas::paint method implemented by the MIDlet developer. The non-Chameleon implementation doesn't, because probably the natives should somehow do it (as you noted).

https://github.com/andreasgal/j2me.js/blob/0647767b7cc968d4b4bbe7dcf3be6ff003964af5/java/midp/javax/microedition/lcdui/CanvasLFImpl.java#L240

I think it's OK if we don't draw the black background, as long as MIDlets don't rely on this behavior.
For correctness sake, I think we should also modify the tests to actually draw a white background and use the images you've generated or modify the tests to draw a black background and keep the old images ((this way, for example, if you execute one of the MIDlets on a real j2me phone, you'll get the same output).
And to avoid headaches in the future, we should also file an issue explaining what we're doing.

**Comment by mykmelez** [comment]
> For correctness sake, I think we should also modify the tests to actually draw a white background and use the images you've generated or modify the tests to draw a black background and keep the old images ((this way, for example, if you execute one of the MIDlets on a real j2me phone, you'll get the same output).
> And to avoid headaches in the future, we should also file an issue explaining what we're doing.

A number of other gfx tests already explicitly draw a white background, so I made these seven tests do the same in c55faf6 and filed #815 to track it.

I also merged from master again.

**Comment by marco-c** [comment]
I think we should also file an issue to remember that we're not doing what we're expected to do (draw a black background), so that if in the future a MIDlet relies on this behavior, we'll know what we have to fix.

**Comment by mykmelez** [comment]
> I think we should also file an issue to remember that we're not doing what we're expected to do (draw a black background), so that if in the future a MIDlet relies on this behavior, we'll know what we have to fix.

Oh, I see. Filed as https://github.com/andreasgal/j2me.js/issues/816!

**Pull request merged**
